default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: negrocu
  password: negrocu

development:
  <<: *default
  database: api_v2

production:
  <<: *default
  database: api_v2_p